export type Search = {budget:number;start:string;end:string;room:string;areas:string[];furnished:boolean;intro:string};
export type Place = {id:string;owner:string;name:string;initials:string;avatar:string;area:string;lat:number;lng:number;price:number;start:string;end:string;room:string;furnished:boolean;checked:boolean;title:string;intro:string;photo:string;likes:number;comments:number;paused?:boolean};
export const photos = ['photo-1522708323590-d24dbb6b0267','photo-1502672260266-1c1ef2d93688','photo-1560448204-e02f11c3d0e2','photo-1484154218962-a197022b5858'].map(id=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1000&q=85`);
export const portraits = ['photo-1494790108377-be9c29b29330','photo-1500648767791-00dcc994a43e','photo-1506794778202-cad84cf45f1d'].map(id=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=120&h=120&q=80`);
export const defaultSearch:Search={budget:950,start:'2027-01-10',end:'2027-05-20',room:'Private room',areas:['Westcott','University Hill'],furnished:true,intro:'Looking for a sunny, furnished room for spring. I’d love to be within walking distance of campus.'};
export const regions:Record<string,[[number,number],[number,number]]>={Westcott:[[43.025,-76.126],[43.044,-76.108]],'University Hill':[[43.027,-76.146],[43.049,-76.127]],Eastside:[[43.025,-76.109],[43.048,-76.087]],Downtown:[[43.041,-76.16],[43.057,-76.143]]};
export const places:Place[]=[
{id:'maya',owner:'maya',name:'Maya R.',initials:'MR',avatar:portraits[0],area:'Westcott',lat:43.036,lng:-76.118,price:820,start:'2027-01-01',end:'2027-06-01',room:'Private room',furnished:true,checked:true,title:'A sunny room, a little closer to everything.',intro:'Heading abroad this spring. My sunny Westcott room is up for grabs! Happy to be flexible on dates.',photo:photos[0],likes:18,comments:2},
{id:'alex',owner:'alex',name:'Alex T.',initials:'AT',avatar:portraits[1],area:'University Hill',lat:43.037,lng:-76.137,price:795,start:'2027-01-01',end:'2027-06-01',room:'Private room',furnished:true,checked:false,title:'Your own room. A porch to share.',intro:'Subleasing my furnished room while I’m away for spring. A short walk to campus and a great little porch.',photo:photos[1],likes:12,comments:0},
{id:'jordan',owner:'jordan',name:'Jordan L.',initials:'JL',avatar:portraits[2],area:'Westcott',lat:43.041,lng:-76.121,price:895,start:'2027-01-01',end:'2027-08-30',room:'Private room',furnished:true,checked:true,title:'Room to make yourself at home.',intro:'A quiet place with plenty of light, plants, and a kitchen worth cooking in. Reach out if it feels like your kind of place.',photo:photos[2],likes:9,comments:0},
{id:'casey',owner:'casey',name:'Casey D.',initials:'CD',avatar:'',area:'Eastside',lat:43.037,lng:-76.103,price:1120,start:'2027-06-01',end:'2027-08-30',room:'Entire place',furnished:true,checked:false,title:'A summer place of your own.',intro:'My one-bedroom is available for summer. Lots of natural light and a little more room to settle in.',photo:photos[3],likes:7,comments:0}];
export const people=[{id:'sam',name:'Sam K.',avatar:portraits[1],search:{...defaultSearch,intro:'Looking for a furnished room near campus for spring. Flexible on the neighborhood and always up for a coffee.'}},{id:'riley',name:'Riley J.',avatar:portraits[2],search:{...defaultSearch,budget:1100,areas:['Westcott','Eastside'],intro:'Moving to Syracuse for the spring. Looking for a comfortable place to land.'}}];
export const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);
export const date=(v:string)=>new Date(v+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'});
export function searchReady(s:Search){return Number.isFinite(s.budget)&&s.budget>0&&!!s.start&&!!s.end&&s.end>s.start&&s.areas.length>0;}
export function fit(p:Place,s:Search,excludeOwned=true):string[]|null{
 if(!searchReady(s)||p.paused||(excludeOwned&&p.owner==='you')||p.price>s.budget||p.start>s.start||p.end<s.end||(s.room!=='Any space'&&s.room!==p.room)||!s.areas.includes(p.area)||(s.furnished&&!p.furnished))return null;
 return ['Within budget','Your dates','In your area',...(s.furnished?['Furnished']:[])];
}
export type Message={from:'you'|'them';text:string};
export type State={onboarded:boolean;active:boolean;ready:boolean;search:Search;searchDraft?:Search;messageDrafts:Record<string,string>;liked:string[];saved:string[];comments:Record<string,string[]>;owned:Place[];threads:Record<string,Message[]>;draftRole:'find'|'offer';draftStep:number;listingDraft:{id?:string;paused?:boolean;title:string;price:number;area:string;start:string;end:string;intro:string;room:string}};
export const initialState:State={onboarded:false,active:false,ready:false,search:defaultSearch,messageDrafts:{},liked:[],saved:[],comments:{},owned:[],threads:{},draftRole:'find',draftStep:0,listingDraft:{title:'',price:850,area:'Westcott',start:'2027-01-01',end:'2027-06-01',intro:'',room:'Private room'}};
export const storageKey='cusesublets-community-concept-v1';
export function readState():State{try{const s=JSON.parse(localStorage.getItem(storageKey)||'null');return s&&typeof s.onboarded==='boolean'&&s.search&&Array.isArray(s.owned)?{...initialState,...s,search:{...defaultSearch,...s.search},listingDraft:{...initialState.listingDraft,...s.listingDraft}}:structuredClone(initialState);}catch{return structuredClone(initialState);}}
