import {useState,type Dispatch,type SetStateAction} from 'react';
import {ArrowLeft,ArrowRight,Home,KeyRound,Check,MapPin,CalendarDays} from 'lucide-react';
import {type State,type Place,regions,photos,portraits,money,date,searchReady} from './model';
import MapPanel from './MapPanel';
export function Welcome({onChoose,onSkip}:{onChoose:(role:'find'|'offer')=>void;onSkip:()=>void}){
 const [role,setRole]=useState<'find'|'offer'>('find');
 return <main className="welcome"><div className="welcome-art"><div className="art-tag"><span className="status-dot"/> Your next chapter starts here.</div><img className="art-home" src={photos[0]} alt="A bright, comfortable apartment"/><div className="art-mini"><img src={photos[1]} alt="A furnished place to stay"/></div><div className="art-person"><img src={portraits[0]} alt="Fictional community member"/><span>A place. A person.<br/><strong>A new beginning.</strong></span></div><div className="art-location"><MapPin size={17}/> Syracuse, NY</div></div><section className="welcome-copy"><span className="eyebrow">A LITTLE MORE COMMUNITY. A LITTLE LESS SEARCHING.</span><h1>What brings<br/>you here?</h1><p>Find a place that fits. Meet the people who make it feel like home.</p><div className="role-options"><button className={'role '+(role==='find'?'selected':'')} aria-pressed={role==='find'} onClick={()=>setRole('find')}><Home/><span><strong>Find a place</strong><small>Meet people. Find your next sublet.</small></span><span className="radio-dot"/></button><button className={'role '+(role==='offer'?'selected':'')} aria-pressed={role==='offer'} onClick={()=>setRole('offer')}><KeyRound/><span><strong>Offer my place</strong><small>Find someone for your space.</small></span><span className="radio-dot"/></button></div><span className="quiet">You can do both. And change your mind anytime.</span><button className="primary full" onClick={()=>onChoose(role)}>Let’s get started <ArrowRight size={18}/></button><button className="text-button skip" onClick={onSkip}>Just exploring? Skip for now <ArrowRight size={15}/></button></section></main>;
}
export default function Setup({state,setState,role,onDone,onLater}:{state:State;setState:Dispatch<SetStateAction<State>>;role:'find'|'offer';onDone:()=>void;onLater:()=>void}){
 const [step,setStep]=useState(state.draftRole===role?state.draftStep:0),[error,setError]=useState('');
 const s=state.searchDraft||state.search,d=state.listingDraft;
 const titles=role==='find'?['When and what feels right?','Where would you feel at home?','A little about your search.']:['Tell us about your place.','Help someone picture living here.','Ready to meet your next subletter?'];
 function search(p:Partial<typeof s>){setState(v=>({...v,searchDraft:{...(v.searchDraft||v.search),...p}}));}
 function listing(p:Partial<typeof d>){setState(v=>({...v,listingDraft:{...v.listingDraft,...p}}));}
 function changeStep(n:number){setStep(n);setError('');setState(v=>({...v,draftRole:role,draftStep:n}));}
 function valid(){if(role==='find'){if(!s.start||!s.end||s.end<=s.start||s.budget<1)return 'Choose a valid date range and monthly budget.';if(step>0&&!s.areas.length)return 'Choose at least one area.';}else{if(!d.title.trim()||d.price<1||!d.start||!d.end||d.end<=d.start)return 'Add a title, monthly rent, and valid dates.';if(step>0&&d.intro.trim().length<10)return 'Write a short introduction (at least 10 characters).';}return '';}
 function next(){const issue=valid();if(issue){setError(issue);return;}if(step<2){changeStep(step+1);return;}if(role==='find'){if(!searchReady(s))return;setState(v=>({...v,search:s,searchDraft:undefined,active:true,ready:true,onboarded:true,draftStep:0}));}else{const bounds=regions[d.area];const p:Place={id:d.id||'own-'+Date.now(),owner:'you',paused:d.paused,name:'You',initials:'Y',avatar:'',area:d.area,lat:(bounds[0][0]+bounds[1][0])/2,lng:(bounds[0][1]+bounds[1][1])/2,price:d.price,start:d.start,end:d.end,room:d.room,furnished:true,checked:false,title:d.title,intro:d.intro,photo:photos[3],likes:0,comments:0};setState(v=>({...v,onboarded:true,owned:d.id?v.owned.map(old=>old.id===d.id?p:old):[p,...v.owned],draftStep:0,listingDraft:{...v.listingDraft,id:undefined,paused:undefined,title:'',intro:''}}));}onDone();}
 return <main className="setup"><div className="setup-heading"><button className="text-button" onClick={()=>step?changeStep(step-1):onLater()}><ArrowLeft size={17}/> Back</button><span className="quiet">{role==='find'?'Your search':'Your listing'} · Step {step+1} of 3</span><button className="text-button" onClick={onLater}>Finish later</button></div><div className="step-track">{[0,1,2].map(i=><span key={i} className={step>=i?'done':''}/>)}</div><h1>{titles[step]}</h1><p className="lead">{role==='find'?'A few details help us connect you with the right places.':'Make a good introduction. You can edit everything later.'}</p><p className="sample-note">Preview mode · Entries are saved only in this browser.</p>
 {role==='find'&&step===0&&<div className="form-grid"><label>Move in<input type="date" value={s.start} onChange={e=>search({start:e.target.value})}/></label><label>Move out<input type="date" value={s.end} onChange={e=>search({end:e.target.value})}/></label><label>Maximum monthly budget<div className="input-prefix"><span>$</span><input type="number" min="1" max="20000" value={s.budget} onChange={e=>search({budget:Number(e.target.value)})}/></div></label><label>Space<select value={s.room} onChange={e=>search({room:e.target.value})}><option>Private room</option><option>Entire place</option><option>Any space</option></select></label><label className="check-row full"><input type="checkbox" checked={s.furnished} onChange={e=>search({furnished:e.target.checked})}/> I need a furnished place</label></div>}
 {role==='find'&&step===1&&<><div className="area-choices">{Object.keys(regions).map(area=><button key={area} className={'chip '+(s.areas.includes(area)?'selected':'')} onClick={()=>search({areas:s.areas.includes(area)?s.areas.filter(a=>a!==area):[...s.areas,area]})}>{s.areas.includes(area)&&<Check size={15}/>} {area}</button>)}</div><MapPanel places={[]} areas={s.areas} large onArea={area=>search({areas:s.areas.includes(area)?s.areas.filter(a=>a!==area):[...s.areas,area]})}/><small className="quiet">Select the areas above or tap a region on the map. These are approximate areas for this preview.</small></>}
 {role==='find'&&step===2&&<><label>Introduce yourself<textarea rows={4} maxLength={800} value={s.intro} onChange={e=>search({intro:e.target.value})} placeholder="A little about you and what you’re looking for…"/></label><div className="setup-summary"><h3>Your search, at a glance</h3><p><Home size={16}/> {s.room} · Up to {money(s.budget)} / month</p><p><CalendarDays size={16}/> {date(s.start)} – {date(s.end)}</p><p><MapPin size={16}/> {s.areas.join(' · ')}</p></div><p className="quiet">Turning this on makes your sample profile visible in this preview. You can turn it off from You at any time.</p></>}
 {role==='offer'&&step===0&&<div className="form-grid"><label className="full">Give your place a title<input value={d.title} maxLength={80} placeholder="A sunny room in Westcott" onChange={e=>listing({title:e.target.value})}/></label><label>Monthly rent<input type="number" min="1" value={d.price} onChange={e=>listing({price:Number(e.target.value)})}/></label><label>Neighborhood<select value={d.area} onChange={e=>listing({area:e.target.value})}>{Object.keys(regions).map(a=><option key={a}>{a}</option>)}</select></label><label>Available from<input type="date" value={d.start} onChange={e=>listing({start:e.target.value})}/></label><label>Available until<input type="date" value={d.end} onChange={e=>listing({end:e.target.value})}/></label><label className="full">Space<select value={d.room} onChange={e=>listing({room:e.target.value})}><option>Private room</option><option>Entire place</option></select></label></div>}
 {role==='offer'&&step===1&&<><img className="setup-photo" src={photos[3]} alt="Sample property photo"/><p className="sample-note">A sample photo is supplied for this preview. Real photo uploads come with the full app.</p><label>What should someone know?<textarea rows={4} maxLength={800} value={d.intro} onChange={e=>listing({intro:e.target.value})} placeholder="Tell them what you love about the place and when it’s available."/></label></>}
 {role==='offer'&&step===2&&<><img className="setup-photo" src={photos[3]} alt="Sample property"/><h2>{d.title}</h2><p>{money(d.price)} / month · {d.area} · {date(d.start)} – {date(d.end)}</p><p>{d.intro}</p><div className="trust-note">You can publish before verification. Your listing will say “Documents not checked” until the appropriate checks are completed. This preview does not accept private documents.</div></>}
 {error&&<p role="alert" className="error">{error}</p>}<div className="setup-footer"><span className="quiet">Your progress is kept in this browser.</span><button className="primary" onClick={next}>{step<2?'Continue':role==='find'?'Turn on my search':d.id?'Save sample listing':'Publish sample listing'}<ArrowRight size={17}/></button></div></main>;
}
